default: # default connection
  type: "sqlite"
  host: "localhost"
  port: 3306
  database: "movie.sqlite"
  synchronize: true
  logging: false
  entities: ["src/Movie/**/*.entity.ts"]
  migrations: ["src/Movie/**/*migration.ts"]
  subscribers: ["src/Movie/**/*subscribers.ts"]
  cli:
    entitiesDir: "src/Movie"
    migrationsDir: "src/Movie"
    subscribersDir: "src/Movie"
